### ISSUE TITLE
INDENTATIONERROR 'EXPECTED AN INTENTED BLOCK'

### ISSUE THREAD

**Issue by supmaxi** [lhr0909/PythonObfuscator#11]
My code is working perfectly fine *before using the obfuscator*, after I use the obfuscator tool, my python code won't run and I receive the following error "IndentationError: ('expected an indented block'"

It would appear to me that the tool is causing some kind of issue with the code? Can you please assist, this tool was what I have been looking for, for so long. =[ Do you have a direct email address?

**Comment by supmaxi** [comment]
Just checked my original code with online tool, and it also found "expected indented block".
But for some reason, before I obfuscate the code, the code still works and runs.
Only when I obfuscate it, does it not allow the program to run

I am closing this issue, as I have confirmed with the online tool that there is an indentation error (or so I assume)

**Comment by lhr0909** [comment]
Let me know if there is anything else you would love me to help. Cheers! There is some bugs that I know are in the current implementation with longer code snippets, which I need to go ahead and fix at some point.

**Comment by supmaxi** [comment]
Hi again, I now have another problem. My code is too large, so the server times out, and im unable to obfuscate the code. I have taken your suggestion of attempting to run the program locally. I have installed Ubuntu on a VM, I have also installed all the required files you mentioned in the text file (argparse, cyclone, pyOpenSSL, twisted, wsgiref, zope interface). Now im stuck, what do i do from here? If i attempt to run (python pyobf.py) in the terminal nothing happens. If i attempt to "execute" pyobf.py, the OS lags for abit, and then I get these "PS" files generated, which are just screenshots (images) called "base64" and "re", and they're simply images of my desktop screen. If I "execute" obfuscatorPage.py , nothing happens. If i attempt to run (python obfuscatorPage.py) in the terminal, I get "twisted.internet.error.cannotlistenerror: couldnt listen on any:5000: [Errno 98] Address already in use"..... Im really stuck right now, where am i suppose to input my original code? How am i suppose to run the program? Can you please help me, I really need to release my program for my customers today, but I dont want to release it before I obfuscate it. Your urgent assistance will be greatly appreciated

**Comment by supmaxi** [comment]
Just to update,  If i attempt to run (python obfuscatorPage.py) it successfully starts listening (i just restarted Ubuntu and it fixed the error I mentioned above). But I still cant work out how to actually use this program. Ive been trying different things for 4 hours straight. If you are reading this please help me lol im going crazy

**Comment by lhr0909** [comment]
Hey man,

so you don't need to run the server (server is really for demo purpose on heroku), you need to write a script to load pyobf.py (all it needs is standard python libs so you shouldn't need to setup anything to use that script), then you just need to run

    obf = pyobf.Obfuscator(string)
    obfuscated = obf.build_simple()

and that should be able to get your code obfuscated. However, as I mentioned before, the script is currently buggy with large source files, your mileage will vary, and I think what you should try is to understand the code (should be a short read), fork, and refine the algorithm to make it more robust.

Let me know if you still have questions. I think that should get you up and running.

**Comment by lhr0909** [comment]
As for installing dependencies in the server, you need to use python-pip (preferably with pyvenv/virtualenv). Once you have those setup, you should be able to run

    pip install

and pip will install those dependencies (cyclone etc) for you based on `requirements.txt`. Hope that speeds up your python development as well! (once you start using package management tools, you can NEVER go back!)

http://docs.python-guide.org/en/latest/dev/virtualenvs/

https://www.dabapps.com/blog/introduction-to-pip-and-virtualenv-python/

**Comment by lhr0909** [comment]
You could try to fork this and deploy on heroku yourself. That way you don't have to pay me for the heroku dyno haha!

**Comment by supmaxi** [comment]
I worked it out!! Thanks so much for your help, much appreciated
