### ISSUE TITLE
No Documentation on Usability : Please advise - Thank you 

### ISSUE THREAD

**Issue by sunshinekingsmile** [lhr0909/PythonObfuscator#12]
Dear Author,

With sincere appreciation, Is it possible to provide simple documentation on how to use this tool.
or it has been here i can't find?
when i get PythonObfuscator, i don't knoe what steps I need follow.
could you provide simple example - this will greatly help
Thank you very much

**Comment by lhr0909** [comment]
Hey, you can refer to #11 . if you want to obfuscate your code locally.
