### ISSUE TITLE
Application error http://pyobf.herokuapp.com/

### ISSUE THREAD

**Issue by hmemar** [lhr0909/PythonObfuscator#13]
When running from the website http://pyobf.herokuapp.com/ the website gives application error.
----------
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.
---------

I am trying to use it locally as per advised since the website is not loading at all.. I was wondering if you can give more help on that and how to do it
When I open the template html and click the submit button it immediately shows me the local drive and nothing else.
please advise

**Comment by lhr0909** [comment]
Hey, for local use please refer to #11 . Thanks!
