### ISSUE TITLE
exceptions.NameError: global name 'base64' is not defined

### ISSUE THREAD

**Issue by yufelixiao** [lhr0909/PythonObfuscator#15]
I use Python 2.4.3 and this PythonObfuscator to obfuscate our python code. Some of obfuscated code runs but for a group of similar python script files, all obfuscated code encounter the same error: exceptions.NameError: global name 'base64' is not defined. Does anyone know how to get rid of this error? Thank you.

**Comment by lhr0909** [comment]
I developed this in Python 2.7.x, and feel free to check the docs about base64 module being in Python 2.4.x or not.
