### ISSUE TITLE
Cant figure it out 

### ISSUE THREAD

**Issue by willbrow** [lhr0909/PythonObfuscator#16]
Hi 

I am running the below in shell
cyclone run '/usr/local/lib/python2.7/site-packages/pyobf/obfuscatorPage.py'

I am getting the error 
No module names pyobf

I think i am setting up incorrectly could anyone point me in the direction of a setup guide please as i really need to use this script 

Thanks

**Comment by lhr0909** [comment]
Hi,

The fastest way to run it is by deploying the app to Heroku. You can fork it and try it on your own Heroku app, if you create one. Otherwise, you can try to do the following

```shell
git clone <repo>
cd <location/of/repo>
pip install
python obfuscatorPage.py
```
